version: '3.7'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: scheduler
    ports:
      - '5432:5432'
  server:
    build: ./server
    volumes:
      - ./server:/app
    environment:
      - DB_URL=postgres://user:pass@db:5432/scheduler
      - JWT_SECRET=changeme
    ports:
      - '3001:3001'
    depends_on:
      - db
  client:
    build: ./client
    volumes:
      - ./client:/app
    ports:
      - '3000:3000'
    depends_on:
      - server
